name: User Service CI/CD

on:
  push:
    branches:
      - app/deployment

jobs:
  deploy:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.17']

    steps:
      - name: Checkout Git Branch
        uses: actions/checkout@v2

      - name: Set Build Tag
        id: build-tag
        run: echo "BUILD_TAG=$(date '+%Y.%m.%d.%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Backend App
        run: |
          cd backend
          npm install
          cd ..

      - name: Install and Build Frontend App
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Build frontend app
        run: npm run build-frontend

      - name: Zip deployment
        run: zip -r deployment-${{ steps.build-tag.outputs.BUILD_TAG }}.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: test-eb-node-js-app
          environment_name: test-eb-node-js-app-env-origin
          version_label: ${{ steps.build-tag.outputs.BUILD_TAG }}
          version_description: ${{ steps.build-tag.outputs.BUILD_TAG }}
          region: us-west-1
          deployment_package: deployment-${{ steps.build-tag.outputs.BUILD_TAG }}.zip
