name: User Service CI/CD

on:
  push:
    branches:
      - app/deployment

jobs:
  deploy:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.17']

    steps:
      - name: Checkout Git Branch
        uses: actions/checkout@v2

      - name: Zip deployment
        run: zip -r deployment-${{ github.SHA }}.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: test-eb-node-js-app
          environment_name: test-eb-node-js-app-env
          version_label: ${{ github.SHA }}
          version_description: ${{ github.SHA }}
          region: us-west-1
          deployment_package: deployment-${{ github.SHA }}.zip
          wait_for_environment_recovery: 60
